/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gym;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import java.sql.ResultSet;

/**
 *
 * @author Admin
 */
public class Member extends javax.swing.JFrame {

    /**
     * Creates new form Member
     */
    public Member() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_mname = new javax.swing.JTextField();
        txt_mnumber = new javax.swing.JTextField();
        txt_mage = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_mamount = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        combo_timing = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txt_coach = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_member = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        combo_gender1 = new javax.swing.JComboBox<>();
        txt_fetch = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txt_m_id = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym/redblack (1).jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        jLabel11.setToolTipText("");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Manage Member");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(310, 0, 195, 32);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Member name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(200, 60, 82, 16);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Phone");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(440, 60, 35, 16);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Age");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(650, 60, 22, 16);

        txt_mname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_mname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_mnameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_mname);
        txt_mname.setBounds(170, 80, 148, 22);

        txt_mnumber.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_mnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_mnumberActionPerformed(evt);
            }
        });
        getContentPane().add(txt_mnumber);
        txt_mnumber.setBounds(390, 80, 155, 22);

        txt_mage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(txt_mage);
        txt_mage.setBounds(620, 80, 114, 22);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Amount");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(6, 145, 45, 16);

        txt_mamount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(txt_mamount);
        txt_mamount.setBounds(63, 142, 85, 22);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Timing");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(204, 145, 38, 16);

        combo_timing.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        combo_timing.setForeground(new java.awt.Color(51, 0, 204));
        combo_timing.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5AM to 8AM", "5PM to 8PM" }));
        getContentPane().add(combo_timing);
        combo_timing.setBounds(248, 142, 104, 22);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Coach");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(418, 145, 33, 16);

        txt_coach.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(txt_coach);
        txt_coach.setBounds(457, 142, 134, 22);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Gender");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(632, 145, 42, 16);

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(180, 210, 130, 23);

        jButton2.setBackground(new java.awt.Color(102, 255, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(350, 210, 130, 23);

        jButton3.setBackground(new java.awt.Color(255, 102, 102));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(520, 210, 130, 23);

        tbl_member.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "Member Name", "Phone", "Age", "Amount", "Timing", "Coach", "Gender", "Title 9"
            }
        ));
        jScrollPane1.setViewportView(tbl_member);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 290, 763, 310);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Member List");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(334, 247, 83, 20);

        combo_gender1.setForeground(new java.awt.Color(255, 0, 51));
        combo_gender1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE", " " }));
        getContentPane().add(combo_gender1);
        combo_gender1.setBounds(700, 140, 77, 22);

        txt_fetch.setBackground(new java.awt.Color(102, 255, 102));
        txt_fetch.setText("fetch");
        txt_fetch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fetchActionPerformed(evt);
            }
        });
        getContentPane().add(txt_fetch);
        txt_fetch.setBounds(10, 210, 132, 23);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("ID");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(60, 60, 13, 16);

        txt_m_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_m_idActionPerformed(evt);
            }
        });
        getContentPane().add(txt_m_id);
        txt_m_id.setBounds(40, 80, 64, 22);

        jButton4.setBackground(new java.awt.Color(153, 0, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setText("Cancel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(690, 210, 130, 23);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym/black-and-red-background-ng8rzw4822lwutyv.jpg"))); // NOI18N
        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(0, 0, 850, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_mnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mnameActionPerformed

    private void txt_mnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mnumberActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            String trainer_id = txt_m_id.getText();
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection conn = DriverManager.getConnection("jdbc:sqlserver://DESKTOP-BLBGEHJ;databaseName=gym;TrustServerCertificate=True;user=gym;password=gym");
            String sql = "exec sp_delete_member ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, trainer_id);

           int i=pst.executeUpdate(); 
           JOptionPane.showMessageDialog(null, "deleted Successful !", "Success", JOptionPane.DEFAULT_OPTION);
    
        }catch(Exception e)
        {
                        
            System.out.print(e);

        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       try{
          
            String mid =txt_m_id.getText();
            String mname =txt_mname.getText();
            String mnumber =txt_mnumber.getText();
            String mage =txt_mage.getText();
            String mamount=txt_mamount.getText();
            String mtime =(String) combo_timing.getSelectedItem();
            String mcoach =txt_coach.getText();
            String mgender=(String) combo_gender1.getSelectedItem();
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection conn = DriverManager.getConnection("jdbc:sqlserver://DESKTOP-BLBGEHJ;databaseName=gym;TrustServerCertificate=True;user=gym;password=gym");
            String sql = "exec sp_update_member ?,?,?,?,?,?,?,?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1,mid );
            pst.setString(2,mname );
            pst.setString(3, mnumber);
            pst.setString(4, mage);
            pst.setString(5,mamount );
            pst.setString(6,mtime );
            pst.setString(7,mcoach );
            pst.setString(8,mgender );
             int i = pst.executeUpdate();
            if (i == 0) {
                JOptionPane.showMessageDialog(null, "Data not updated");
            } else {
                JOptionPane.showMessageDialog(null, "Data updated successfully");
            }
        } catch (Exception ex) {
          //  JOptionPane.showMessageDialog(null, ex);
                        System.out.println(ex);

        }

            
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_fetchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fetchActionPerformed
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection conn = DriverManager.getConnection("jdbc:sqlserver://DESKTOP-BLBGEHJ;databaseName=gym;TrustServerCertificate=True;user=gym;password=gym");
            String sql = "sp_fetch_member";
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            tbl_member.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception ex) {
            System.out.println(ex);
        }

    }//GEN-LAST:event_txt_fetchActionPerformed

    private void txt_m_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_m_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_m_idActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            
            String mid =txt_m_id.getText();
            String mname =txt_mname.getText();
            String mnumber =txt_mnumber.getText();
            String mage =txt_mage.getText();
            String mamount=txt_mamount.getText();
            String mtime =(String) combo_timing.getSelectedItem();
            String mcoach =txt_coach.getText();
            String mgender=(String) combo_gender1.getSelectedItem();
            
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection conn = DriverManager.getConnection("jdbc:sqlserver://DESKTOP-BLBGEHJ;databaseName=gym;TrustServerCertificate=True;user=gym;password=gym");
            String sql = "exec sp_addmember ?,?,?,?,?,?,?,?";
             PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1,mid );
            pst.setString(2,mname );
            pst.setString(3, mnumber);
            pst.setString(4, mage);
            pst.setString(5,mamount );
            pst.setString(6,mtime );
            pst.setString(7,mcoach );
            pst.setString(8,mgender );
            
            int i=pst.executeUpdate();
            if (i == 0) {
        JOptionPane.showMessageDialog(null, "Data not inserted");
    } else {
        JOptionPane.showMessageDialog(null, "Data inserted successfully");
    }
} catch (Exception ex) {
  //  JOptionPane.showMessageDialog(null, ex);
                System.out.println(ex);
    
}
 
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
             dispose();
                home Home=new home();
                Home.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Member().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo_gender1;
    private javax.swing.JComboBox<String> combo_timing;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_member;
    private javax.swing.JTextField txt_coach;
    private javax.swing.JButton txt_fetch;
    private javax.swing.JTextField txt_m_id;
    private javax.swing.JTextField txt_mage;
    private javax.swing.JTextField txt_mamount;
    private javax.swing.JTextField txt_mname;
    private javax.swing.JTextField txt_mnumber;
    // End of variables declaration//GEN-END:variables
}
