/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package blood;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author Admin
 */
public class availabledoner extends javax.swing.JFrame {

    /**
     * Creates new form Search
     */
    public availabledoner() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_fetch = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_doneravailable = new javax.swing.JTable();
        btn_fetch1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Available Doner");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(330, 30, 210, 32);

        btn_fetch.setBackground(new java.awt.Color(153, 255, 153));
        btn_fetch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_fetch.setText("Fetch doner");
        btn_fetch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fetchActionPerformed(evt);
            }
        });
        getContentPane().add(btn_fetch);
        btn_fetch.setBounds(70, 80, 110, 23);
        getContentPane().add(jLayeredPane1);
        jLayeredPane1.setBounds(380, 190, 0, 0);

        tbl_doneravailable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        jScrollPane2.setViewportView(tbl_doneravailable);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(30, 130, 760, 382);

        btn_fetch1.setBackground(new java.awt.Color(255, 51, 51));
        btn_fetch1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_fetch1.setText("Cancel");
        btn_fetch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fetch1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_fetch1);
        btn_fetch1.setBounds(660, 80, 110, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blood/image-1200x700.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 840, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents
          
    private void btn_fetchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fetchActionPerformed
                   PreparedStatement pst  = null ;
        try{
         
          Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver"); 
          Connection conn=DriverManager.getConnection("jdbc:sqlserver://DESKTOP-BLBGEHJ;databaseName=blood;TrustServerCertificate=True;user=saba;password=saba");
          String sql="exec sp_fetchuser";
            
          pst = conn.prepareStatement(sql);
    if (pst != null) {
        ResultSet rs = pst.executeQuery();
        tbl_doneravailable.setModel(DbUtils.resultSetToTableModel(rs));
    } else {
        System.out.println("PreparedStatement is null");
    }
    
    
    
         // conn.prepareStatement(sql);
        //  System.out.println("connection done");
          
         //  ResultSet rs = pst.executeQuery();
      //     if (rs != null) {
//        tbl_doneravailable.setModel(DbUtils.resultSetToTableModel(rs));
//    } else {
//        System.out.println("ResultSet is null");
//    }
         // System.out.println("fetch done");
          
    //  tbl_doneravailable.setModel(DbUtils. resultSetToTableModel(rs));
        
           }
       catch (Exception ex)
           {
       System.out.println(ex);
        //   JOptionPane.showMessageDialog(null, "could not fetch. Please try again"); 
           } 
        
        
    }//GEN-LAST:event_btn_fetchActionPerformed

    private void btn_fetch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fetch1ActionPerformed
        // TODO add your handling code here:
           
      dispose();
        home HOME=new home();
        HOME.setVisible(true);
    }//GEN-LAST:event_btn_fetch1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(availabledoner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(availabledoner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(availabledoner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(availabledoner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new availabledoner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_fetch;
    private javax.swing.JButton btn_fetch1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_doneravailable;
    // End of variables declaration//GEN-END:variables
}
