/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package blood;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class newuser extends javax.swing.JFrame {

    /**
     * Creates new form newuser
     */
    public newuser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_submitn = new javax.swing.JButton();
        btn_newuser = new javax.swing.JButton();
        txt_name = new javax.swing.JTextField();
        txt_pwd = new javax.swing.JTextField();
        txt_uname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("NEW USERS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(114, 34, 102, 25);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("User name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(76, 144, 60, 16);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Pass word");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(81, 194, 55, 16);

        btn_submitn.setBackground(new java.awt.Color(153, 204, 0));
        btn_submitn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_submitn.setText("submit");
        btn_submitn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitnActionPerformed(evt);
            }
        });
        getContentPane().add(btn_submitn);
        btn_submitn.setBounds(81, 241, 72, 23);

        btn_newuser.setBackground(new java.awt.Color(255, 153, 153));
        btn_newuser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_newuser.setText("login");
        btn_newuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newuserActionPerformed(evt);
            }
        });
        getContentPane().add(btn_newuser);
        btn_newuser.setBounds(179, 241, 100, 23);

        txt_name.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(txt_name);
        txt_name.setBounds(162, 101, 109, 22);

        txt_pwd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_pwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pwdActionPerformed(evt);
            }
        });
        getContentPane().add(txt_pwd);
        txt_pwd.setBounds(162, 191, 109, 22);

        txt_uname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(txt_uname);
        txt_uname.setBounds(162, 141, 109, 22);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(97, 101, 31, 16);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blood/istockphoto-1302642699-612x612.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 370, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents
 PreparedStatement pst = null;
    private void btn_submitnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitnActionPerformed
        // TODO add your handling code here:
        try{
            String name = txt_name.getText();
            String username = txt_uname.getText();
            String password = txt_pwd.getText();

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection conn=DriverManager.getConnection("jdbc:sqlserver://DESKTOP-BLBGEHJ;databaseName=blood;TrustServerCertificate=True;user=saba;password=saba");
            System.out.println("connection done");
            String sql="exec sp_newuser ?,?,?";

            pst = conn.prepareStatement(sql);
             pst.setString(1,name);
            pst.setString(2,username);
            pst.setString(3,password);

          int i = pst.executeUpdate();
        if (i > 0) {
            JOptionPane.showMessageDialog(null, "data inserted");
        } else {
            JOptionPane.showMessageDialog(null, "data not inserted");
        }
        System.out.println("if else completed");
    } catch (Exception ex) { 
       
         JOptionPane.showMessageDialog(null,ex.toString());
    }
       
    }//GEN-LAST:event_btn_submitnActionPerformed

    private void btn_newuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newuserActionPerformed
        // TODO add your handling code here:
                   dispose();
                login Login=new login();
              Login.setVisible(true);
    }//GEN-LAST:event_btn_newuserActionPerformed

    private void txt_pwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pwdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newuser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_newuser;
    private javax.swing.JButton btn_submitn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_pwd;
    private javax.swing.JTextField txt_uname;
    // End of variables declaration//GEN-END:variables
}
